services:
  - type: web
    name: expense-tracker-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests -B
    startCommand: java -Dspring.profiles.active=prod -Dserver.port=$PORT -Xmx512m -jar target/expense-tracker.jar
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: JAVA_OPTS
        value: "-Xmx512m -XX:+UseSerialGC"