services:
  - type: web
    name: expense-tracker-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests -B
    startCommand: ./start.sh
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
      - src/**
      - pom.xml
      - start.sh
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/./urandom"
      - key: PORT
        value: "8080"